language: python
python:
    - "2.7"

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=arduino/AnalogInToESC/*.ino
    - PLATFORMIO_CI_SRC=arduino/AnalogJoystickControl/*.ino
    - PLATFORMIO_CI_SRC=arduino/BareMinimum/*.ino
    - PLATFORMIO_CI_SRC=arduino/I2CControl/*.ino

install:
    - pip install -U platformio

script:
    - platformio ci --board=uno --board=megaatmega2560